### ISSUE TITLE
Better mirror scale domain calculation with Extent transform

### ISSUE THREAD

**Issue by arvind** [vega/vega-dataflow#16]
The extent transform currently only calculates the extent of a single field. Vega scales, however, may have domains defined over multiple fields (for example, as produced by Vega-Lite for binned fields). To be able to interactively manipulate the domains of these scales, it would be useful for the extent transform to be able to similarly calculate a single extent over a group of fields.  

```json
"domain": {
  "data": "summary",
  "fields": [
    "bin_Miles_per_Gallon_start",
    "bin_Miles_per_Gallon_end"
  ]
}
```

**Comment by arvind** [comment]
Adding `zero` and `round` parameters to the extent transform would be similarly helpful to ensure parameterized scale domains are correctly initialized. In Vega-Lite, these properties can no longer be set on the scales directly, if they are parameterized by a selection, because they would interfere with the ability to pan and zoom.

**Comment by jheer** [comment]
vega-dataflow already includes multi-domain facilities by combined use of the `Extent` and `MultiExtent` operators. However, the `MultiExtent` transform is not exposed as a Vega transform. In addition, neither supports `zero` or `nice` (note that `round` is a scale range option, not a domain option). This is all by design, to keep the dataflow simple and streamlined. For example, there is no single correct way to compute `nice` boundaries for a scale domain, as this depends on the scale type.

To serve the use case you describe, I recommend trying another approach that instead uses two scales: one for domain computation and another to drive visual encoding. Here's a sketch:
```js
"signals": [
  {"name": "scaleDomain1", "update": "domain('scale1')"},
  {"name": "scaleDomain2", /* perform logic for the ultimate domain value */}
],
"scales": [
  {"name": "scale1", "domain": /* desired domain definition, zero, nice, etc */},
  {"name": "scale2", "domain": {"signal": "scaleDomain2"}}
],
```

So the actual data flow goes: `scale1 -> scaleDomain1 -> scaleDomain2 -> scale2`. The signal updates for `scaleDomain2` can then use `scaleDomain1` plus any other signals, etc to determine the actual domain to use in the visualization. This approach involves a bit of overhead with a "proxy" scale, but should give you full flexibility regardless of scale type. It also lets you use the built-in multi-domain determination in a direct fashion.

Let me know if this suffices for you, and if so, go ahead and close the issue.

**Comment by arvind** [comment]
Oh that's clever! Let me try that and report back.

**Comment by jheer** [comment]
Did it work? Can we close out this issue?

**Comment by arvind** [comment]
Yes indeed it does. Thanks!
